import memberImage from "./assets/memberImage.png"

export default [
  {
    id: 1,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 2,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 3,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 4,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 5,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 6,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 7,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 8,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 9,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 10,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 11,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 12,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
  {
    id: 13,
    memberImage: memberImage,
    memberTitle: "Web Dev",
    memberName: "John Doe",
    memberInstagramLink: "",
    memberEmailLink: "",
    memberLinkedinLink: "",
  },
];